Some steps in tasks in the student guide have been updated.
microsoft/MCW-App-modernization pull request #67
Opened 2020-10-22 06:30 UTC by ddobric

Due to portal changes and some issues in the provisioned environment Some steps in tasks in the student guide have been updated.

2020-10-23 16:21 UTC, kylebunting commented
@DawnmarieDesJardins, this pull request contains changes to make notes about differences when running the lab using a pre-provisioned environment. From previous conversations, I was under the impression that we were keeping the lab guides focused on provisioning using the associated ARM templates and setup steps.

Has the stance on this changed and do we want those kinds of changes coming into the labs?

If so, these changes look good. Otherwise, I think we should leave them out.

2020-10-23 18:32 UTC, DawnmarieDesJardins commented
@kylebunting - Thanks for the review Kyle, you are correct.

@ddobric - Damir - Thank you for reaching out!  Due to the broad reach of our workshops, they are written as if there is no pre-provisioned environment.  If students are using a partner environment to work through the lab, they would be given additional instructions as needed by the lab hosts.

Closing PR with no further action.

2020-11-02 07:41 UTC, ddobric commented
But changes in this PR also contain many other issues that are not related to the provisioned environment.

2020-11-02 18:19 UTC, timahenning commented
@ddobric I have Kyle to review the changes.

2020-11-03 22:43 UTC, kylebunting requested changes
@ddobric, please review my comments below, remove the few lines specific to using a pre-provisioned environment, and then I think we can pull in the other changes.

Thanks!

2020-11-03 22:43 UTC, kylebunting commented on Hands-on lab/HOL step-by-step - App modernization.md
> +   > **Note**: If creation fails, you may need to select **Advanced settings** and specify the subscription, region and resource group for the new storage account. This will create the new storage ac
This change is good and should be incorporated into the current lab guide.

2020-11-03 22:43 UTC, kylebunting commented on Hands-on lab/HOL step-by-step - App modernization.md
> +   Alternatively, you can create the new storage account on your own. In that case please use 'locally redundant zone', because other options are disabled by the policy.
This change is good and should be incorporated into the current lab guide.

2020-11-03 22:43 UTC, kylebunting commented on Hands-on lab/HOL step-by-step - App modernization.md
> + > **Note**: The name of your VM with the SQL server is different if you work in the provisioned lab environment. Use ```-n Sql2008-*****```
This change is specific to using a pre-provisioned environment and should not be included in the pull request.

2020-11-03 22:43 UTC, kylebunting commented on Hands-on lab/HOL step-by-step - App modernization.md
> + The right name can be obtained from the resource list in the Azure portal.
This change is specific to using a pre-provisioned environment and should not be included in the pull request.

2020-11-03 22:43 UTC, kylebunting commented on Hands-on lab/HOL step-by-step - App modernization.md
> +> **Note**: If you have multiple Azure subscriptions, and the account you are using for this hands-on lab is not your default account, you may need to run `az account list --output table` at the Azur
This text is from the current workshop and does not appear to have been changed.

2020-11-03 22:43 UTC, kylebunting commented on Hands-on lab/HOL step-by-step - App modernization.md
> +>NOTE: If you are working in the lab environment, you might get following error:
This change is specific to using a pre-provisioned environment and should not be included in the pull request.

2020-11-03 22:43 UTC, kylebunting commented on Hands-on lab/HOL step-by-step - App modernization.md
> +This command sets the read permission on the resource group.
This change is good and should be incorporated into the current lab guide.

2020-11-12 18:05 UTC, timahenning commented
Hi @ddobric,

Some of your changes in the submitted PR for the MS master update are great catches and can be accepted.  Kyle has made comments about some of the changes that need to be removed.  They cannot be accepted because they pertain to a pre-provisioned environment.  If you can make those recommended changes, we can get your updates merged into the master branch.  The other option is keep your changes in your local branch.

Let us know soon. Thanks.

Tim

2020-12-21 20:08 UTC, DawnmarieDesJardins commented
@ddobric 
Hi Damir.  Thanks for looking at this.  Due to current issues, we are starting a refresh of this workshop that will incorporate your requests.  Please look for that to be complete mid-February.  For now, closing your PR to move forward with the workshop refresh.

2020-12-21 20:08 UTC, closed without merging